version: "3.1"

services:
  mongo:
    container_name: fathers-db
    image: mongo:4.4.4-bionic
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: father
      MONGO_INITDB_ROOT_PASSWORD: father
