version: 2.1
jobs:
  unit-tests:
    working_directory: ~/app
    docker:
      - image: cimg/node:14.18.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-unit-dependencies-{{ checksum "yarn.lock" }}
            - v4-unit-dependencies-
      - run:
          name: Yarn install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v3-unit-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run Jest tests
          command: yarn test
  integration-tests:
    docker:
      - image: cimg/node:14.18.2
      - image: mongo:4.4.4-bionic
        environment:
          MONGO_INITDB_ROOT_USERNAME: father
          MONGO_INITDB_ROOT_PASSWORD: father
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-unit-dependencies-{{ checksum "yarn.lock" }}
            - v4-unit-dependencies-
      - run:
          name: Yarn install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v3-unit-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Start
          command: yarn start:dev
          background: true
      - run:
          name: Wait-on http://localhost:3000
          command: npx wait-on http://localhost:3000
      - run:
          name: Run Integration tests
          command: yarn test:integration
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-unit-dependencies-{{ checksum "yarn.lock" }}
            - v2-unit-dependencies-
      - run:
          name: Write build tag
          command: sh ./scripts/generate-version.sh
      - run:
          name: Build Docker image
          command: sh ./scripts/push.sh
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v2-unit-dependencies-{{ checksum "yarn.lock" }}
workflows:
  final_build:
    jobs:
      - integration-tests
      
