version: 2.1
jobs:
  unit-tests:
    working_directory: ~/app
    docker:
      - image: cimg/node:14.18.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-unit-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-unit-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run Jest tests
          command: yarn test
  integration-tests:
    docker:
      - image: mcr.microsoft.com/playwright:focal
        environment:
          WOOCOMMERCE_URL: $WOOCOMMERCE_URL
          WOOCOMMERCE_KEY: $WOOCOMMERCE_KEY
          WOOCOMMERCE_SECRET: $WOOCOMMERCE_SECRET
      - image: mongo:4.4.4-bionic
        environment:
          MONGO_INITDB_ROOT_USERNAME: father
          MONGO_INITDB_ROOT_PASSWORD: father
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-unit-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-unit-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Copy shared env vars from app
          command: |
            cat .env-integration > .env
      - run:
          name: Start
          command: yarn start:dev
          background: true
      - run:
          name: Wait-on http://localhost:3000
          command: npx wait-on http://localhost:3000
      - run:
          name: Run Integration tests
          command: yarn test:integration
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-unit-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Write build tag
          command: sh ./scripts/generate-version.sh
      - run:
          name: Build Docker image
          command: sh ./scripts/push.sh
      - save_cache:
          paths:
            - node_modules
          key: v1-unit-dependencies-{{ checksum "yarn.lock" }}
workflows:
  final_build:
    jobs:
      - unit-tests
      - integration-tests
      - build
      
